### ISSUE TITLE
Victoria

### ISSUE THREAD

**Issue by SteveModz** [Kerillian/Mayfly#1]
Hello, this isn't a issue but is there any chance you could send me your lavalink.jar file? As the ones I've tried in my bot state that the websocket isn't open?

**Comment by Kerillian** [comment]
The one I'm using comes directly from the [original v3.4 release on their page](https://github.com/freyacodes/Lavalink/releases/tag/3.4). I never built my own. Just make sure your `application.yml` isn't malformed.
